CREATE DATABASE BAKERY;
USE BAKERY;
CREATE TABLE ADMIN
(
ID VARCHAR(30) PRIMARY KEY,
PASS VARCHAR(30),
NAME VARCHAR(30)
);
INSERT INTO ADMIN
VALUES("Admin","Admin","Admin Default");

CREATE TABLE SALES
(
SALES DECIMAL(6,2),
DATE DATE
);

CREATE TABLE CASHIER
(
NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
MOBILE INT NOT NULL,
ID VARCHAR(30) PRIMARY KEY,
PASS VARCHAR(30)
);

INSERT INTO CASHIER
VALUES("Cashier Default","CashierDefault@CashierDefault.com",7894561320,"Cashier","Cashier");

CREATE TABLE ITEM
(
NAME VARCHAR(30) NOT NULL,
PRICE DECIMAL(5,2) NOT NULL,
STOCK INT(5),
CODE VARCHAR(30) PRIMARY KEY
);

